Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Mechanic> Mechanics { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<MechanicMachine> MechanicMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<MechanicMachine>();
    }

    public int MachineId { get; set; }
    public string Description { get; set; }

    public virtual ICollection<MechanicMachine> JoinEntities { get;}
  }
}

Factory/Models/Mechanic.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Mechanic
  {
    public Mechanic()
    {
      this.JoinEntities = new HashSet<MechanicMachine>();
    }

    public int MechanicId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<MechanicMachine> JoinEntities { get; set; }
  }
}

Factory/Models/MechanicMachine.cs
namespace Factory.Models
{
  public class MechanicMachine
  {       
    public int MechanicMachineId { get; set; }
    public int MachineId { get; set; }
    public int MechanicId { get; set; }
    public virtual Machine Machine { get; set; }
    public virtual Mechanic Mechanic { get; set; }
  }
}

Factory/Models/StringFactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Mechanic> Categories { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<MechanicMachine> MechanicMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MechanicId = new SelectList(_db.Mechanics, "MechanicId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int MechanicId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() { MechanicId = MechanicId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Mechanic)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.MechanicId = new SelectList(_db.Mechanics, "MechanicId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int MechanicId)
    {
      if (MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() { MechanicId = MechanicId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMechanic(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.MechanicId = new SelectList(_db.Mechanics, "MechanicId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddMechanic(Machine machine, int MechanicId)
    {
      if (MechanicId != 0)
      {
      _db.MechanicMachine.Add(new MechanicMachine() { MechanicId = MechanicId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMechanic(int joinId)
    {
      var joinEntry = _db.MechanicMachine.FirstOrDefault(entry => entry.MechanicMachineId == joinId);
      _db.MechanicMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/MechanicsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MechanicsController : Controller
  {
    private readonly FactoryContext _db;

    public MechanicsController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Mechanic> model = _db.Mechanics.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Mechanic mechanic)
    {
      _db.Mechanics.Add(mechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMechanic = _db.Mechanics
          .Include(mechanic => mechanic.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }
    public ActionResult Edit(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost]
    public ActionResult Edit(Mechanic mechanic)
    {
      _db.Entry(mechanic).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      _db.Mechanics.Remove(thisMechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the String Factory!</h1>
<p>@Html.ActionLink("See all machines", "Index", "Machines")</p> <p>@Html.ActionLink("See all mechanics", "Index", "Mechanics")</p>

Factory/Views/Machines/AddMechanic.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a mechanic</h2>

<h4>Add a mechanic to this machine: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select mechanic")
  @Html.DropDownList("MechanicId")

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new machine</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  @Html.Label("Select mechanic")
  @Html.DropDownList("MechanicId")

  <input type="submit" value="Add new machine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine does not belong to any mechanics</p>
}
else
{
  <h4>Mechanics the machine belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Mechanic.Name</li>
    @using (Html.BeginForm("DeleteMechanic", "Machines"))
    {
      @Html.Hidden("joinId", @join.MechanicMachineId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add a Mechanic", "AddMechanic", new { id = Model.MachineId })</p>

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.Label("Select mechanic")
  @Html.DropDownList("MechanicId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
} 

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.Description}", "Details", new { id = machine.MachineId })</li>
}

<p>@Html.ActionLink("Add new machine", "Create")</p>

Factory/Views/Mechanics/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h4>Add a new mechanic</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new mechanic" />
}
<p>@Html.ActionLink("Show all mechanics", "Index")</p>

Factory/Views/Mechanics/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Mechanics/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic;

<h2>Mechanic Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This mechanic does not maintain any machines</p>
}
else
{
  <h4>Machines the mechanic maintains:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Machine.Description</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to Mechanics", "Index")</p>
<p>@Html.ActionLink("Edit Mechanic", "Edit", new { id = Model.MechanicId })</p>
<p>@Html.ActionLink("Delete Mechanic", "Delete", new { id = Model.MechanicId })</p>

Factory/Views/Mechanics/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Edit</h2>

<h4>Edit this mechanic: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MechanicId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Mechanics/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Mechanics</h1>

@if (@Model.Count == 0)
{
  <h3>No mechanics have been added yet!</h3>
} 

<ul>
  @foreach(Mechanic mechanic in Model)
  {
    <li>@Html.ActionLink($"{mechanic.Name}", "Details", new { id = mechanic.MechanicId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new mechanic", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Shared/Footer.cshtml
<footer id="footer">@Html.ActionLink("Home", "Index", "Home")</footer>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My String Factory!</title>
    <link rel="stylesheet" href="~/css/styles.css"> 
  </head>
  <body>
    @RenderBody()
    @Html.Partial("Footer")
  </body>
</html>